
<div class="zerogrid">
		<div class="wrap-footer">
			<div class="row">
				<div class="col-1-4">
					<div class="wrap-col">
						<div class="widget wid-about">
							<div class="wid-header">
								<h5>Welcome</h5>
							</div>
							<div class="logo"><a href="index.php"><img src="images/rena.png"/></a></div>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
				<div class="col-1-4">
					<div class="wrap-col">
						<div class="widget wid-meta">
							<div class="wid-header">
								<h5>Facebook</h5>
							</div>
							<div class="widget-content">
								<div class="row">
									<ul>
										<li><img src="images/Facebook.png"></li>
										
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-1-4">
					<div class="wrap-col">
						<div class="widget wid-tag">
						<div class="wid-header">
							<h5>Twitter</h5>
						</div>
						<div class="widget-content">
								<div class="row">
									<ul>
										<li><img src="images/Twitter.png"></li>
										
									</ul>
								</div>
							</div>
					</div>
					</div>
				</div>
				<div class="col-1-4">
					<div class="wrap-col">
						<div class="widget wid-meta">
							<div class="wid-header">
								<h5>Google+</h5>
							</div>
							<div class="widget-content">
								<div class="row">
									<ul>
										<li><img src="images/Youtoube.png"></li>
										
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
   <div class="bottom-footer">
		<div class="wrap-bottom ">
			<div class="copyright">
				<p>Designed @ Horizon IT Services </p>
			</div>
		</div>
	</div> 