<div class="wrap-sidebar">
					<!---- Start Widget ----><!---- Start Widget ---->
			    <div class="widget wid-tag">
						<div class="wid-header">
							<h5>MISSION</h5>
						</div>
						<div class="wid-content">At Horizon IT Services, we believe in looking towards the future with endless 
						inventions in developing technologies, products and services to suit our customers&rsquo; needs today and in the future.</div>
				  </div>
			    <!---- Start Widget ----><!---- Start Widget ----><!---- Start Widget ----></div>