<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>HORIZON IT SERVICES </title>
	<meta name="description" content="Web Development, Bauchi,Web Programming, Nigeria,Website Design,Web Developers, Web Designers, Web Coding, HTML5,CSS, JQuery,"
    >
	<meta name="author" content="www.horizon.com.ng">
	
    <!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
  	<link rel="stylesheet" href="css/zerogrid.css">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/responsive.css">
    <link rel="shortcut icon" href="images/eeee.ico" />
	
	<!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="js/html5.js"></script>
		<script src="js/css3-mediaqueries.js"></script>
	<![endif]-->
    
</head>
<body>
<div class="wrap-body">

<!--////////////////////////////////////Header-->

<header>
<section id="container">
	<div class="wrap-container clearfix">
	<div class="top-bar">
		<div class="wrap-top zerogrid">
			<div class="row">
				<div class="col-1-2">
					<div class="wrap-col">
						<ul>
							<li class="mail"><p>info@horizon.com.ng</p></li>
							<!--<li><p style="color:#FFF"><img src="images/reg.png"  height="30" width="30"/></p></li>-->
						</ul>
					</div>
				</div>
				<div class="col-1-2">
					<div class="wrap-col f-right">
						<div class="top-social">
							<a href="#"><img src="images/Facebook.png" title="facebook"/></a>
							<a href="#"><img src="images/Twitter.png" title="twitter"/></a>
							<a href="#"><img src="images/Skype.png" title="google"/></a>
							<a href="#"><img src="images/Pinterest.png" title="pinterest"/></a>
							<a href="#"><img src="images/Youtoube.png" title="instagram"/></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="wrap-header">
		<div class="zerogrid">
			<div class="row">
				<div class="col-1-3">
					<div class="wrap-col">
						<div class="logo"><a href="index.php"><img src="images/rena.png"/></a></div>	
					</div>
				</div>
				<div class="col-2-3">
					<div class="wrap-col f-right">
						<ul>
							<li>  <h5><?php
		 echo (date("l: dS \ F, Y. ")); 
		?> </h5> <p></p>
								<form method="get" action="/search" id="search" >
								  <input name="q" type="text" size="40" placeholder="Search..." />
								</form>
							</li>
							
                            
						</ul>
					</div>
				</div>
			</div>
		</div>